comment_id = "eff710f0-d67a-11e7-920e-d53b2bdd726d"
slug = "firefox-57-cpu-usage-is-insane"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Hey, I'm really bummed about it as well. Not sure what it is, I've read that people are having the same issue on both Windows and Mac. Maybe it is a combination of both hardware and software.\n\nHopefully, 58 will bring a solution for it.\n\nCheers!"
date = "2017-12-01T09:35:16.284Z"
