comment_id = "4179c730-ca91-11ea-9c4a-178f7ba63703"
slug = "letters-from-sarajevo"
name = "mensur"
email = "332e40241647a21e715b5950cadd0eea"
message = "i ti sarajlija? što me iznenadi naslov, rekoh štaaaa"
date = "2020-07-20T13:59:40.744Z"
