comment_id = "7299ffe0-e6d0-11e6-bdca-7de5d7664428"
slug = "mobile-chrome-vh-units-fix"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Hi Adam,\n\nIt is missing, thanks for pointing it out. I just added MIT license to the repository.\n\nCheers!"
date = "2017-01-30T09:42:43.612Z"
layout = "verslag"
excerpt_separator = "<!--more-->"
