comment_id = "7065d740-e6cf-11e6-bdca-7de5d7664428"
slug = "mobile-chrome-vh-units-fix"
name = "Adam"
email = "2ef9b8c8f6eacec56ec204211b8cc9bf"
message = "Hi,\n\nCan't see any mention of your vh-fix license in GitHub. Technically this means \"all rights reserved\". Is this accurate, or is the license just missing?\n\nMany Thanks,\n\nAdam"
date = "2017-01-30T09:35:30.385Z"
layout = "verslag"
excerpt_separator = "<!--more-->"
