comment_id = "e2d52000-5399-11e8-8290-8bfe9ef925e3"
slug = "mobile-chrome-vh-units-fix"
name = "Pierre"
email = "e0122651354bfe7d62a46bcc3a74561a"
message = "I just had a question about usage.  I am using vh to define the size of all of my headings.  Can I just use the body selector with a height of  100vh so all my responsive headings work?"
date = "2018-05-09T15:01:44.043Z"
timestamp = 1525878104
tags = []
