comment_id = "64e56f00-8797-11e9-881b-59dc537dbfe4"
slug = "mobile-chrome-vh-units-fix"
name = "Miklos"
email = "f9948268935b8e5e9c388e12816871df"
message = "This is great, thanks.\nHowever, it worked for me by replacing the last line of js file with this:\n\nelement.domElement.style.height = (document.documentElement.clientHeight * element.vh / 100)   'px';"
date = "2019-06-05T13:39:51.698Z"
