comment_id = "8b3dd2f0-c666-11ea-a3b0-b1256315c642"
slug = "macos-catalina-ruby-bad-interpreter-error"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Thank you both for the kind words!\n\nAnd I hear you, it is a simple one, but was super hard for me to pinpoint it.\n\nCheers!"
date = "2020-07-15T06:43:51.472Z"
