comment_id = "ac5d7a50-d316-11ea-83f0-ff1c7aa534ea"
slug = "macos-catalina-ruby-bad-interpreter-error"
name = "Adrian"
email = "f10fa0bb5c1dc5ad2d699ca90f7315eb"
message = "yeah, thanks 1!"
date = "2020-07-31T10:14:52.427Z"
