# GitHub
username: Stanko
repo: Stanko.github.io
branch: master

# Jekyll source / destination
source: .
destination: _site

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: '/:title/'
plugins:
- jekyll-paginate
- jekyll-octicons
- jekyll-redirect-from

# Plugins which are activated by default

# - jekyll-coffeescript
# - jekyll-gist
# - jekyll-github-metadata
# - jekyll-relative-links
# - jekyll-optional-front-matter
# - jekyll-readme-index
# - jekyll-default-layout
# - jekyll-titles-from-headings

# Plugins allowed by GitHub Pages

# - jekyll-coffeescript
# - jekyll-feed
# - jekyll-gist
# - jekyll-github-metadata
# - jekyll-paginate
# - jekyll-redirect-from
# - jekyll-seo-tag
# - jekyll-sitemap
# - jekyll-avatar
# - jemoji
# - jekyll-mentions
# - jekyll-relative-links
# - jekyll-optional-front-matter
# - jekyll-readme-index
# - jekyll-default-layout
# - jekyll-titles-from-headings
# - jekyll-include-cache
# - jekyll-octicons

exclude:
 - node_modules
 - gulpfile.babel.js
 - package.json
 - _sass
# - public/css # gulp injects CSS via browsersync
 - _js
 - .sass-cache
 - Gemfile
 - Gemfile.lock
 - vendor

# Setup
title: Muffin Man
tagline: Frontend development & rants
description: Hello, I'm Stanko, a software engineer in Belgrade, writing mostly about JavaScript and React.
url: http://stanko.github.io
baseurl: ''
paginate: 5
paginate_path: 'page-:num'
excerpt_separator: <!--more-->

# About/contact
author:
  name: Stanko
  url: http://stanko.github.io

# Live reload
reload_port: 5678
