comment_id = "f4a83de0-1eb2-11ea-87a5-031b984a5832"
slug = "nvm-updating-npm"
name = "C. L. Jones"
email = "47c9cee8f047c083eca9829cc1a869d8"
message = "Nice find, Shawn!  Exactly what I needed :)."
date = "2019-12-14T20:47:34.837Z"
