comment_id = "0d607f00-d659-11e6-8bb2-9de7d4ed7dc2"
slug = "setting-up-webpack-babel-and-react-from-scratch"
name = "Darrell"
email = "c6c37c4c0d6395bc9a4f45e69bc8bdb4"
message = "Hey Stanko!\n\nThanks for an excellent tutorial. Any chance you could add the complete config file at the end of your post as you suggested? And perhaps the package.json file as well? And does the .babelrc file go in the root directory? A lot of questions :)"
date = "2017-01-09T10:47:45.084Z"
