comment_id = "c5cd3a20-e440-11e6-adcc-5fca9f7acef0"
slug = "setting-up-webpack-babel-and-react-from-scratch"
name = "Pedro"
email = "5bddaf6fb08719ce86756591e45bc200"
message = "Just an addition to Jack's comment, whenever one needs to show a patch in a file, I find that including one line before and one after the relevant lines makes everything clearer. I've seen articles where the author would go as far as to post the actual diffs from commits. I did manage to follow through the edits with no problem though.\n\nThat said, nice tutorial, although with a bit too much of loose ends, relying a lot on external guides. I also noticed react-router is missing from your final package.json, shouldn't it be there?\n\nAnyway, looking forward to see the next updates, thanks!"
date = "2017-01-27T03:29:13.379Z"
layout = "verslag"
excerpt_separator = "<!--more-->"
