comment_id = "5a35f500-02f8-11e7-9cfb-db5ce023a11d"
slug = "setting-up-webpack-babel-and-react-from-scratch"
name = "Payal"
email = "3aee79ea94dbdae98de203b28cf6bf29"
message = "Wonderful article. Thanks for sharing Stanko."
date = "2017-03-07T05:38:55.100Z"
