comment_id = "d14b2030-1927-11e7-924d-b313c1e1b5eb"
slug = "setting-up-webpack-babel-and-react-from-scratch"
name = "Ram Kinkar"
email = "9f353e47186389154da26ffe3cb9e18b"
message = "thanks for this helpful article!"
date = "2017-04-04T11:14:06.832Z"
