comment_id = "a7e098c0-71f2-11ea-a4b4-f58fb02115e2"
slug = "three-js-extrude-svg-path"
name = "Victor Wei"
email = "e2454a6f25b3a3413d5d4f84b0b1a2ac"
message = "Is there a way to support colored SVG's?"
date = "2020-03-29T19:22:40.329Z"
