comment_id = "42cde8e0-f1ca-11ea-894e-1b3701341697"
slug = "three-js-extrude-svg-path"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Thank you very much for the explanation tuseroni!\n\nThis is brilliant, I'm going to try it and update the article!\n\nCheers!!"
date = "2020-09-08T11:55:59.578Z"
