comment_id = "56cfab20-4262-11ea-96a1-b3095fd7ae2a"
slug = "get-scrollbar-width-in-javascript"
name = "Patrick"
email = "174f6e51426a507ac64e26b2d641cd28"
message = "Really elegant solution (which actually works!). Why (on earth) are there so many solutions which create a div"
date = "2020-01-29T06:41:12.066Z"
