comment_id = "33ff3a80-7f74-11ea-80bb-c75574bffbca"
slug = "fix-lumpy-joy-con-using-hair-dryer"
name = "Ali"
email = "06c0c614573c9b413a5619d1fd81b57e"
message = "I realize this article is super old, but I foolishly removed my rubber cap from the joy con stick thinking there was debris underneath only to discover those little inserts. Well trying to realign one or two is a challenge, but trying to realign all of them seems impossible. Anyone have any ideas?"
date = "2020-04-15T23:52:45.526Z"
