comment_id = "cc1719a0-caec-11ea-9cb8-8bdbcc372613"
slug = "fix-lumpy-joy-con-using-hair-dryer"
name = "Quincy"
email = "8e0a0580afdc590684d954a7c9e5ebab"
message = "So I found an effective approach when trying to put the cap back on. If you're fortunate to have a small flathead or hex screwdriver set, you can use the head to maneuver the pin into place and press down on it from the top, it took me about 5 minutes, but I was able to get all of them reseated."
date = "2020-07-21T00:54:57.545Z"
