comment_id = "dc22c300-d3d2-11ea-bbfa-45d047792330"
slug = "fix-lumpy-joy-con-using-hair-dryer"
name = "Ectopic"
email = "8a982a68267318bd16a093b3c04f67d5"
message = "The rubber ridges on the inside have tiny finger-like projections which point outwards towards the rim. With the edge of the rubber cap bent backwards, you need a tiny flathead screwdriver to push the tip of these rubber fingers into the corresponding groove before flipping the rubber rim over the stick."
date = "2020-08-01T08:41:57.952Z"
