comment_id = "86205fb0-1ab9-11e7-9d22-9b434ef38faa"
slug = "setting-up-webpack-babel-and-react-from-scratch-part-2"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Hello Vladislav,\n\nYeah, javascript development sure can be a bumpy road. I'm really glad it helped you!"
date = "2017-04-06T11:09:38.410Z"
