comment_id = "94d01230-2f2d-11eb-bfe4-9f8f24367c94"
slug = "hack-for-ios-safari-to-display-html-video-thumbnail"
name = "Andres"
email = "fa41b5f61f15d0165190e9c7c52848dd"
message = "Muchas gracias, funciono, estuve 1 mes tratando de solucionar esto en una app con cordova phonegap.\n\n\n<small>Edit by Stanko (I used Google to translate it):</small>\n\nThank you very much, it worked, I spent 1 month trying to solve this in an app with cordova phonegap."
date = "2020-11-25T14:50:38.372Z"
