comment_id = "9251edf0-b04e-11e7-a288-11368df4174b"
slug = "webpack-babel-react-revisited"
name = "Josh Habdas"
email = "bda486b80a2e80a8e22afe69dd621303"
message = "Don't reinvent the wheel. The best boilerplates have already been invented and are listed right here: https://habd.as/awesome-react-boilerplates/\n\nP.s. Nice design on this site."
date = "2017-10-13T19:41:57.006Z"
