comment_id = "07fa99f0-ac29-11e7-86ab-5f3848337529"
slug = "webpack-babel-react-revisited"
name = "Abhirup Kundu"
email = "84cb31c4e72cd6314f8e7931967339cc"
message = "Excellent tutorial. Very well written and explained. Helped me a lot."
date = "2017-10-08T13:03:08.991Z"
