comment_id = "c21c5cd0-abd2-11e7-86ab-5f3848337529"
slug = "webpack-babel-react-revisited"
name = "RL Glover"
email = "a379820e1c6d0cb7b2f3945416bd87b1"
message = "Powerful tutorial obviously created by an exceptional visionary. Highly recommended for the consummate professional."
date = "2017-10-08T02:45:35.089Z"
