comment_id = "126b1990-b03a-11e7-a288-11368df4174b"
slug = "webpack-babel-react-revisited"
name = "Rafael Rinaldi"
email = "ffc5102ee85d0d7ec57200fa3e6b1fce"
message = "It's great to see an up to date and battle tested perspective on the subject. Very helpful, thank you."
date = "2017-10-13T17:15:12.581Z"
