comment_id = "bb0034a0-b04e-11e7-a288-11368df4174b"
slug = "webpack-babel-react-revisited"
name = "Josh Habdas"
email = "bda486b80a2e80a8e22afe69dd621303"
message = "I do hope you'll post my comment, as I'm shilling but it's good for the community to know about. You should be more open with your comment policy."
date = "2017-10-13T19:43:05.254Z"
