comment_id = "5e18c640-af17-11e7-8129-4b38db0f8264"
slug = "webpack-babel-react-revisited"
name = "gbarkhatov"
email = "de455f69cfcb84eea06820bd44f7d44c"
message = "Hey man. Waiting for the new things from you. Is there a way to subscribe to your blog? Maybe rss or kinda"
date = "2017-10-12T06:34:16.000Z"
