comment_id = "daceef60-b134-11e7-badf-f3eff1f658c7"
slug = "webpack-babel-react-revisited"
name = "Rahmat Budiharso"
email = "e58c3d651de4a8ba2eba2764f7f44fbd"
message = "Thank you for the post, it's just what I needed. I'm constantly battling with webpack configuration and those \"boilerplate\" got too much magic for me to understand which part doing what, hope to see another post just like this."
date = "2017-10-14T23:10:22.974Z"
