comment_id = "b04387c0-b246-11e7-8411-e99c61e7b1a5"
slug = "webpack-babel-react-revisited"
name = "Petar"
email = "e38b301cb294b14cf00e946fe8f48173"
message = "Great article. It might be useful to add links to parts of the page with a content at the beginning so people can jump to certain parts, also safari seems to have a weird bug when scrolling up and down on this page :p (I use it to test stuff, sue me). Keep it up :)"
date = "2017-10-16T07:50:38.212Z"
