comment_id = "96e133d0-b12f-11e7-badf-f3eff1f658c7"
slug = "webpack-babel-react-revisited"
name = "Mathew Cohen"
email = "c0cacca053f25dd2c938f4219e8481ff"
message = "So... uh... \n\nD:\\__MyCodingProjects\\__TestingGround\\WebackAndBabel>./node_modules/webpack/bin/webpack.js ./src/js/app.js --output-filename ./dist/app.bundle.js\n'.' is not recognized as an internal or external command,\noperable program or batch file."
date = "2017-10-14T22:32:41.511Z"
