comment_id = "e86192e0-b40e-11e7-bd17-5d42f2395bbf"
slug = "webpack-babel-react-revisited"
name = "James"
email = "a26b0dfbfa4d159c509e6f739edf2c0d"
message = "@Anthony:\n\nThe basics of adding SASS are pretty easy. First `npm i -D node-sass sass-loader`, and then update the CSS module loader rule to this:\n\n<pre>{\n    test: /\\.scss$/,\n    loader: ExtractTextPlugin.extract({\n        // Loader chaining works from right to left\n        use: ['css-loader', 'sass-loader']\n    })\n} </pre>\n\nOnce you rename your style.css file to style.scss and update the `import` reference in app.js, you should be good to go!"
date = "2017-10-18T14:16:18.363Z"
