comment_id = "f8207df0-b403-11e7-bd17-5d42f2395bbf"
slug = "webpack-babel-react-revisited"
name = "Tuhaj"
email = "edc0a75b36f5ee1e9181acbc9cf2b311"
message = "Hey! Very nice tutorial, I appreciate your work Stanko. For all who are interested in using existing boilerplates I had a presentation at WarsawJS it where I compared the features them, so you can have a look if you want https://youtu.be/E7hbVm9Fh9w"
date = "2017-10-18T12:58:00.228Z"
