comment_id = "04481b90-be38-11e7-adcc-4d581267522b"
slug = "webpack-babel-react-revisited"
name = "Matteo"
email = "a67b90d89d9f8d13b40fa28f46518b04"
message = "Thank you very much for this awesome tutorial!"
date = "2017-10-31T12:35:46.193Z"
