comment_id = "502843a0-cd60-11e7-8c80-d5c6356d83c9"
slug = "webpack-babel-react-revisited"
name = "Laurynas"
email = "df1e8f0fac2e3dc450c84d0e9bb23d28"
message = "Excellent tutorial! Thanks a lot!"
date = "2017-11-19T19:32:00.781Z"
