comment_id = "054e4f80-ddca-11e7-a0c1-7de20d8f0c32"
slug = "webpack-babel-react-revisited"
name = "Chris"
email = "a6d14de05d7b2c3cf4fae7ae14cfa7f3"
message = "This was a great help, thank you."
date = "2017-12-10T16:49:00.601Z"
