comment_id = "1f5ad7b0-d9b3-11e7-b1ed-e53bbb450d54"
slug = "webpack-babel-react-revisited"
name = "yinfan"
email = "08b9dd82fe5a9a020c3a0d2f5958c768"
message = "Thank you very much, Great tutorial!"
date = "2017-12-05T11:55:01.084Z"
tags = [ "" ]
