comment_id = "6c82d550-dce3-11e7-be15-a3469e549c00"
slug = "webpack-babel-react-revisited"
name = "Jarno"
email = "44fa12113195b46e5796f55a655f5cf3"
message = "Thank you, great tutorial.. Cant wait for the SASS post :)"
date = "2017-12-09T13:18:19.925Z"
