comment_id = "f795b590-d69e-11e7-920e-d53b2bdd726d"
slug = "webpack-babel-react-revisited"
name = "aldhonie"
email = "cac05e716ba2466fbf557ec945289f2f"
message = "Awesome, Thanks a lot stanko. Youre doing a good job!"
date = "2017-12-01T13:53:10.953Z"
