comment_id = "2b3d5b80-e001-11e7-8a64-79051c54fa43"
slug = "webpack-babel-react-revisited"
name = "Sergiu Lucaci"
email = "e88d0d6693dbdbf035793ee29f8e80ca"
message = "Though I work with both React and Webpack 1 for some time, this article helped gave me a clearer image about how Webpack actually works. \n\nGG Stanko!"
date = "2017-12-13T12:28:48.786Z"
