comment_id = "e2125ff0-ec85-11e7-9e3d-bfba8dc81df7"
slug = "webpack-babel-react-revisited"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Thanks everyone!\n\n@Joisak, there is no need to alter <code>webpack.config</code>, just start making your components in <code>src/js/</code> folder."
date = "2017-12-29T10:49:02.900Z"
