comment_id = "b0dc75a0-f0be-11e7-83bb-b50b8e36fc3b"
slug = "webpack-babel-react-revisited"
name = "Dana Yudelevich"
email = "a8a30575e21bd2fe9469c22567730656"
message = "Great tutorial @stanko! Adding SASS would definitely be a good step to add."
date = "2018-01-03T19:45:46.316Z"
timestamp = 1515008746
