comment_id = "d98e4c80-ff69-11e7-8ffb-11b63858d020"
slug = "webpack-babel-react-revisited"
name = "madushan"
email = "a2185f11f441629c1df038b9c807db66"
message = "really nice one thanks for the effort. looking forward to having some example of redux"
date = "2018-01-22T11:46:14.890Z"
