comment_id = "8d616c90-0b33-11e8-b84f-75476b51bc09"
slug = "webpack-babel-react-revisited"
name = "Rahul"
email = "2eff2bedc96191885173bf9f235c1751"
message = "Thank you for this wonderful tutorial. It helped me understand a lot of basic things and gave me a good idea about how to put things together and how things work under the hood."
date = "2018-02-06T11:47:48.277Z"
timestamp = 1517917668
