comment_id = "7160ce00-3b67-11e8-b042-4d6d56584300"
slug = "webpack-babel-react-revisited"
name = "Olatunji Yusuf"
email = "e1e4143ccf0438a1acbad88b804ee69d"
message = "Excellent Stuff!"
date = "2018-04-08T20:00:10.915Z"
layout = "post"
