comment_id = "26e628d0-a5e2-11e8-a8ee-834e779b59e8"
slug = "webpack-babel-react-revisited"
name = "SomeDevRevisiting"
email = "9d8a458ef23b9f72a5788494b84cb1f3"
message = "Awesome tutorial! Explanations are not that long but contains the important stuff!"
date = "2018-08-22T08:05:37.332Z"
