comment_id = "bece68f0-87a6-11e9-881b-59dc537dbfe4"
slug = "webpack-babel-react-revisited"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Hi Kumar,\nUnfortunately I have no production experience with Vue.js\n\nCheers!"
date = "2019-06-05T15:29:45.284Z"
