comment_id = "f4451130-1061-11e9-955b-a1039fd26a7c"
slug = "javascript-time-ago-function"
name = "Achim"
email = "db312cb8f87252c749e7656cb8ed294f"
message = "Hi,\nthank you. It saved me some time.\nI wrote a query function to automatically update the dates:\n\n\n[code removed]"
date = "2019-01-04T20:47:31.161Z"
