comment_id = "d8ee4d30-a254-11ea-a2bb-7d47da971828"
slug = "javascript-time-ago-function"
name = "McAustin"
email = "3028e1e1877bed7e39dbcb0411f8b48d"
message = "it didn't work for me saying today @ particular time frame,"
date = "2020-05-30T09:06:29.023Z"
