comment_id = "3cad0d50-a257-11ea-a2bb-7d47da971828"
slug = "javascript-time-ago-function"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "McAustin, it seems your comment got cut off. Can you please provide a test case that didn't work? And the solution if you figured it out.\n\nCheers!"
date = "2020-05-30T09:23:35.368Z"
