comment_id = "504f1ba0-e45b-11ea-874d-813967426640"
slug = "javascript-time-ago-function"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Thanks guys!\n\nelijah, I just created a demo on Codepen, I added it <a href=\"#demo\">at the bottom of the post</a>. Hope that helps!\n\nCheers!"
date = "2020-08-22T09:39:03.004Z"
