comment_id = "a657d930-afe8-11ea-89d9-9d0c27914563"
slug = "simple-javascript-api-wrapper"
name = "LKG"
email = "8cbdecf8aa4305f84db9151d1d3b75cb"
message = "Thank you. I will be using this on a future project of mine. I have been looking for a wrapper class that handles errors"
date = "2020-06-16T15:47:14.941Z"
