comment_id = "4f77d340-d8d7-11e6-98fc-772cf35a194b"
slug = "ios-safari-scoll-position-fixed"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Thank you both, Matt for the tip and anarchimedes for the feedback.\n\n\nI hope you don't mind I added it to the article as well."
date = "2017-01-12T14:56:34.857Z"
data = "2017-01-12T14:56:34.857Z"
