comment_id = "b2395590-160c-11e7-951e-15ced69e6d88"
slug = "ios-safari-scoll-position-fixed"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Haha thanks a lot Zack! :) no worries, you made my day, that's enough!"
date = "2017-03-31T12:22:24.858Z"
