comment_id = "38cc62e0-1582-11e7-bddc-ed6a4b7bfabf"
slug = "ios-safari-scoll-position-fixed"
name = "Zack"
email = "ca514406df630aaa426fd6f61f38c33f"
message = "Wow, if you had a donate button on this article I would pay you. You fixed my issue of hours of research!"
date = "2017-03-30T19:51:10.515Z"
timestamp = 1490903470
