comment_id = "c368b4c0-3185-11e7-b336-bf9d2ea0e954"
slug = "ios-safari-scoll-position-fixed"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Hello Jonathan, probably something else in your code removed it. CSS property can't be <i>canceled</i> by itself."
date = "2017-05-05T11:27:04.087Z"
