comment_id = "56812dc0-3184-11e7-b336-bf9d2ea0e954"
slug = "ios-safari-scoll-position-fixed"
name = "Johnthan"
email = "388f5101e0730cb5b08e4dde4fd67ce2"
message = "Thanks for the article I tried it directly on my element fixed, but the fixed position somehow got canceled?"
date = "2017-05-05T11:16:51.895Z"
