comment_id = "bd89dfe0-5c53-11e7-8740-611bb057eb94"
slug = "ios-safari-scoll-position-fixed"
name = "Michel"
email = "78c1164f8d597845a9f275ee5bf37648"
message = "Hey, I need to understand one thing, i must to apply `translate3d` at every element that it will pass scroll through the fixed element?"
date = "2017-06-28T22:47:19.459Z"
layout = "post"
aanwezig = true
nieuwe_inschrijving = false
