comment_id = "c6e7fc30-8e66-11e7-b692-5be3d941184b"
slug = "ios-safari-scoll-position-fixed"
name = "Jeka"
email = "bfaffd290e45cbe007f149b48e70b07d"
message = "God bless you, my friend! It's works like a miracle!"
date = "2017-08-31T16:09:33.733Z"
timestamp = 1504195773
