comment_id = "18f15750-55c8-11e8-9ca2-03d586cce74d"
slug = "ios-safari-scoll-position-fixed"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Hello @thangavel,\n\nI've stripped huge chunk of code you posted in your comment. It was unreadable, next time please try making example on codepen or jsbin.\n\nCheers!"
date = "2018-05-12T09:37:33.940Z"
timestamp = 1526117853
tags = [ "comment-subscription" ]
