comment_id = "8e04f480-f729-11e9-80ab-25a600b0cb36"
slug = "ios-safari-scroll-position-fixed"
name = "Krish"
email = "8d033a980eace8a7a8f1c83adbff8b65"
message = "Matt, when I have a input at the bottom of the page and on its focus, I get extra white space while scrolling. How to get rid of this white space. \n\nThe parent div is fixed."
date = "2019-10-25T13:15:46.318Z"
