comment_id = "95d73c80-468f-11ea-870b-0bccc77ad3ff"
slug = "ios-safari-scroll-position-fixed"
name = "Dasha"
email = "d5466c662caef1719e10d2143729703f"
message = "I have the same issue. \n\nWhen I have a input at the bottom of the page and on its focus, I get extra white space while scrolling. How to get rid of this white space.\n\nHas someone found a solution ?\n\nThanx)"
date = "2020-02-03T14:15:10.049Z"
