comment_id = "eff93330-5675-11ea-bd38-71aeed885fdc"
slug = "running-staticman-on-heroku"
name = "Igor Kowalczyk"
email = "28a451314d9295e9bcce66c293bd20ed"
message = "Really god article"
date = "2020-02-23T19:51:52.732Z"
