comment_id = "8a983190-1643-11e8-b1fd-f167a257a673"
slug = "react-router-subfolder-on-server"
name = "Wilfried"
email = "fab3e7160014f8a2cf2af8dfea52734b"
message = "Thank you, helped me to solve my routing problem on sub folders."
date = "2018-02-20T13:39:58.208Z"
