comment_id = "0129ff40-212b-11e8-aa9c-dfa80684aaf4"
slug = "react-router-subfolder-on-server"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "As I mentioned in the article already, the biggest drawback is that you'll have <code>/#/</code> in your URLs."
date = "2018-03-06T10:42:02.670Z"
