comment_id = "617f8ba0-575b-11e9-8b54-315bf370ae21"
slug = "react-router-subfolder-on-server"
name = "Shubham Kesarwani"
email = "5a416c13b2a788e31bf2246e0f553bd7"
message = "In my case there are two projects in two different subdirectories. and based on request i want to redirect to that particular project.\n\nFor e.g. \nwww.test.com/us should go to project residing in 'us' directory\nand\nsame should happen with www.test.com/in \n\n\nRewriteRule ^ /path/to/subfolder/index.html [L]\nHow can I get subfolder dynamically from url.\n\nPlease help"
date = "2019-04-05T04:29:20.524Z"
