comment_id = "26e14a40-d403-11e9-985e-d7733b393af6"
slug = "react-router-subfolder-on-server"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "That is correct Dave, I just updated the post.\n\nCheers!"
date = "2019-09-10T19:42:42.182Z"
