comment_id = "fe44e6d0-2012-11ea-bffe-5d8553fd4a3a"
slug = "react-router-subfolder-on-server"
name = "Catarina"
email = "766a8b6025ce7c94d48af02473cf98b4"
message = "Hi! \nIt helps me in some things but I still can't use routes. I got error 404.\nI'm using create-react-app and the project is hosted on iis\nSomeone can help?"
date = "2019-12-16T14:47:33.834Z"
