comment_id = "9fddd460-c15b-11e8-9259-3970a6205b11"
slug = "uploading-files-using-fetch-multipart-form-data"
name = "Stanko"
email = "muffinman"
message = "You made my day, thank you! :) Glad I could help."
date = "2018-09-26T07:13:10.668Z"
