comment_id = "ee1491e0-4f68-11ea-9348-77cba8fc1d33"
slug = "fix-for-chrome-not-rendering-borders"
name = "André"
email = "56b505fdfee5ccd82fcda2dfec6e23b9"
message = "Fantastic!! Thanks"
date = "2020-02-14T20:31:08.024Z"
