comment_id = "bf869490-4b26-11ea-a974-836c634d18bc"
slug = "fix-for-chrome-not-rendering-borders"
name = "Jimmie D Reed"
email = "c12d33b691b1ed4bf715ddbbae6b5e21"
message = "hey. found this via google.. WORKED!!"
date = "2020-02-09T10:27:18.431Z"
