comment_id = "4e6310e0-9200-11e7-83e6-5f4ca8e9a40d"
slug = "react-rerender-in-component-did-mount"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "You are welcome :) And thank you, I'm doing my best to write about real problems I encounter.\n\nCheers!"
date = "2017-09-05T06:06:07.397Z"
timestamp = 1504591567
