comment_id = "33f21b50-a80f-11e7-8704-5b582ac668d2"
slug = "react-rerender-in-component-did-mount"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Hello Jimmy,\nI'm sorry to hear it didn't work for you. Method works for sure, as you can see from the examples. I used it numerous times. You can check <a href=\"https://muffinman.io/react-animate-height/\">react-animate-height</a> which is using it as well.\n\n<code>ReactTransitionGroup</code> and <code>ReactCSSTransitionGroup</code> are out for a while, but they do a little bit different thing. \n\nMethod I described is meant for a simple two-states animations. For such things I prefer doing it on my own rather than pulling whole library. Plus it gives you more control.\n\nCheers!"
date = "2017-10-03T07:48:11.212Z"
