comment_id = "751a85f0-a768-11e8-9d49-9fff9455a2a1"
slug = "small-mac-apps-i-love"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Hello Serdar,\n\n\nNice find, thanks for sharing! It looks similar to Spectacle.\n\n\nCheers!"
date = "2018-08-24T06:39:32.225Z"
