comment_id = "4a70ca40-bbe9-11e8-89fb-bde33cd2d3fe"
slug = "add-git-version-tag-after-publishing-to-npm"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Hey Mikhail,\n\nI wasn't aware of <a href=\"https://docs.npmjs.com/cli/version\">npm version</a>. Thank you for pointing it out.\n\nCheers!"
date = "2018-09-19T08:52:08.892Z"
