comment_id = "eb1b40d0-054b-11eb-b7ef-ed5eec2daedc"
slug = "deprecating-marvin"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Hey ismael, your comment made my day :) thank you for the kind words!"
date = "2020-10-03T07:41:59.408Z"
