comment_id = "5d120cf0-8e51-11e9-9af4-e3fe0b134b1f"
slug = "sektor-draw-and-animate-svg-circle-sectors-2016"
name = "Bean Wong"
email = "d58f13a332e9292c9f0bdf269555b936"
message = "Thanks for your reply Stanko, can i have a example to how to pass the \"angle\" to a easing function?"
date = "2019-06-14T03:06:12.425Z"
