comment_id = "caa38a90-a3d0-11e7-adb3-e700074bdbd8"
slug = "travis-jekyll-and-github-pages"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Hello Lars,\n\nI'll take a look, but I can't promise anything :)\n\nMeanwhile I have a cheesy advice - you could clone my blog's repo, and replace the posts and theme.\n\nBtw how are you doing it at the moment, are you building it locally and pushing everything to <code>gh-pages</code> by hand?\n\nCheers!"
date = "2017-09-27T22:11:21.057Z"
