comment_id = "082b0290-a443-11e7-adb3-e700074bdbd8"
slug = "travis-jekyll-and-github-pages"
name = "Lars Olesen"
email = "610f737eb11bb06b5b915b40bcdb2b87"
message = "I know there is no promises :) Right now, I just let Github take care of the building in the `gh-branch`. Basically, the dfference might be that it is not a user or organization website?"
date = "2017-09-28T11:49:06.920Z"
