comment_id = "e77ee810-a3c8-11e7-adb3-e700074bdbd8"
slug = "travis-jekyll-and-github-pages"
name = "Lars Olesen"
email = "610f737eb11bb06b5b915b40bcdb2b87"
message = "I've been trying a lot of different setups to get https://github.com/vih/historie/tree/master to work using this setup, but nothing is working for me so far. Maybe you have the magic word and can see what my mistake is?"
date = "2017-09-27T21:14:53.498Z"
