comment_id = "49edb390-d426-11e7-b97f-857bbc4913b3"
slug = "my-two-cents-on-the-new-macbook-pro"
name = "Marko"
email = "dbff46b78089bbefe28c8e67948a8492"
message = "I agree. You should switch to surface book 2."
date = "2017-11-28T10:24:17.644Z"
