comment_id = "fac23820-a217-11e8-81a4-e32088d3b40d"
slug = "mobile-chrome-vh-units-fix"
name = "Stanko"
email = "muffinman"
message = "Hello Dusan,\nI've just tested it on iPad simulator and it works as expected.\n\n\nCheers!"
date = "2018-08-17T12:20:51.465Z"
