comment_id = "00fd6ca0-78f1-11e8-9b58-1bb68f7113a8"
slug = "uploading-files-using-fetch-multipart-form-data"
name = "Sam"
email = "f84baa981fe11d79b14e6869f2e4e4f4"
message = "Thank you so much! Spent hours wrapping my brain around this till I read this article!"
date = "2018-06-26T03:28:33.718Z"
