comment_id = "379fe080-c063-11e8-b2a1-7ff8a07e6dfe"
slug = "uploading-files-using-fetch-multipart-form-data"
name = "Mohammad"
email = "d407d899b7b4d578b3a965a07bdefa70"
message = "Thank you so much!\n\nso much!\n\nso much!\n\nso much!\n\nso much!\n\nso much!\n\nso much!\n\n\n I Spent more than 2 days  searching for posible problem\nbecause the post request succeed with Postman and failed when i use  Angular 6 HttpClient and Django Rest Framework\n\nthen at 2:30 am i found your  article!\n\ni hope that you add more search key for exp HttpClient of Angular and Django Rest Famework so when some novice faces that problem they can find answers\n\nyou're the best"
date = "2018-09-25T01:35:00.636Z"
