comment_id = "df807620-c1cb-11e8-9259-3970a6205b11"
slug = "uploading-files-using-fetch-multipart-form-data"
name = "Katie"
email = "20ed88af2693783985cd4e2ad9ddba90"
message = "Thank you! This was a huge help!"
date = "2018-09-26T20:36:41.331Z"
