comment_id = "b7f44bf0-e9c5-11e8-8f2a-8feed3d3f9b7"
slug = "uploading-files-using-fetch-multipart-form-data"
name = "Barbara"
email = "2cabe5e1f90ee4306cf89a1246e160ad"
message = "This FINALLY solved the issue I'd been having for hours, thank you so much!!!"
date = "2018-11-16T17:33:24.238Z"
