comment_id = "5c6518c0-56a6-11e9-8cc4-fb9b5a7b7b56"
slug = "uploading-files-using-fetch-multipart-form-data"
name = "karan"
email = "58e5d54f59f348497ab10002613557d7"
message = "hey, where exactly should we put this?"
date = "2019-04-04T06:53:33.085Z"
