comment_id = "9166c260-dde9-11e9-9f72-29b900de9415"
slug = "uploading-files-using-fetch-multipart-form-data"
name = "Serkan Atasagun"
email = "fe39704e6f3109d284a6d49d0e471a57"
message = "You’ve saved my day. Thanks so much!"
date = "2019-09-23T10:04:44.989Z"
