comment_id = "86c7a820-31fd-11ea-9814-87f9081fbbbb"
slug = "uploading-files-using-fetch-multipart-form-data"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Hey Dave,\n\n<code>fetch</code> accepts two params, <code>url</code> and <code>options</code>. So before calling it, make sure your options are not including Content-Type header.\n\nTo answer your question, delete Content-Type header right before you call fetch.\n\nCheers!"
date = "2020-01-08T09:59:14.706Z"
