comment_id = "cf17bbb0-3c2f-11ea-b5cb-3b285db94673"
slug = "uploading-files-using-fetch-multipart-form-data"
name = "HONGIL"
email = "96bea999e1a078fc1d3a857e5f8ee120"
message = "Hey.\n\nThank you for your posting.\nMy upload is now working.\n\nyou save my evening.\n\nCheers!"
date = "2020-01-21T09:24:22.741Z"
