comment_id = "54dad3a0-5b06-11ea-aaa0-a95a5fb54914"
slug = "uploading-files-using-fetch-multipart-form-data"
name = "Ramesh"
email = "1bae86eb5def3c7ff1e7800794c2c778"
message = "You made my day! Thank you so much. I was having trouble in uploading photo in react native."
date = "2020-02-29T15:15:34.158Z"
