comment_id = "250b6eb0-74aa-11ea-b8e1-1d5d312ddffe"
slug = "uploading-files-using-fetch-multipart-form-data"
name = "Faysal Bsata"
email = "b8f39c49e8e26cd1246c8ebc8e2b34d8"
message = "You are an angel from god.\nThank you I've wasted a day and a half trying to diagnose the issue. \nThank you <3"
date = "2020-04-02T06:21:10.472Z"
