comment_id = "6b9f3440-74c0-11ea-a51d-2fe7fbd98934"
slug = "uploading-files-using-fetch-multipart-form-data"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "You are welcome! I had no idea this is an issue for so many people, glad I could help."
date = "2020-04-02T09:00:37.887Z"
