comment_id = "96257ae0-babf-11ea-8229-93009baaafd2"
slug = "uploading-files-using-fetch-multipart-form-data"
name = "Jordi"
email = "726ef9300dc93c6f9ecf258e4c76d598"
message = "I spent 3 hours because of that lil' `contentType: 'multipart/form-data'`. Luckilly I stumbled upon your post. Thank you so much"
date = "2020-06-30T10:51:01.019Z"
