comment_id = "707b9110-b77e-11ea-9b20-c556a2edab34"
slug = "uploading-files-using-fetch-multipart-form-data"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Hello Sanyukta,\nI think you just need to update the field name, from <code>files</code> to <code>files[]</code>. For multiple files, field needs to be an array.\n\nCheers!"
date = "2020-06-26T07:27:07.048Z"
