comment_id = "582c1f80-457c-11eb-ac73-1db927a27700"
slug = "uploading-files-using-fetch-multipart-form-data"
name = "Renato"
email = "d47b7cd15176fce0f8eb2ee5e905d56d"
message = "That doesnt make sense\n\nthere is no Content-Type do delete after set options without Content-Type key\n\nconst options = { method: 'POST', body: formData };\ndelete options.headers['Content-Type'];\n\nIts the same as just\nconst options = { method: 'POST', body: formData };"
date = "2020-12-24T00:09:52.625Z"
