comment_id = "0a928e10-2963-11eb-aab5-4bfbcf25969f"
slug = "disable-cmd-mouse-wheel-zoom-in-firefox"
name = "Tim"
email = "10865625d89b084ca028fbf476dac340"
message = "Thank you!!! This was driving me mad as well. 3 second fix. 🙌"
date = "2020-11-18T05:58:12.243Z"
