comment_id = "960fc130-6564-11e8-bad2-cb2ae67b23b7"
slug = "plx-react-parallax-component"
name = "Valerii"
email = "5778a7aeeb55a505b3bf994afc194c97"
message = "Hi from Ukraine!\n\nI have used your awesome component!\n\nYou can check it follow the link, not brilliant work but it`s my first parallax page.\n\nico.experitus.com\n\nThanks for component:)"
date = "2018-06-01T06:25:32.798Z"
timestamp = 1527834332
tags = [ "comment-subscription" ]
