comment_id = "43620b70-3e9c-11e9-aec3-5186d7c4cdd5"
slug = "plx-react-parallax-component"
name = "Stanko"
email = "13a28fac985c11eb7f40169be7da32f4"
message = "Hey Ryan,\n\nThank you for the praise, I'm doing my best :)\n\nI've tried Plx <a href=\"https://muffinman.io/react-plx/\">demo</a> on both iOS and Android phones, and it works smoothly.\n\nThere are couple of things that might affect performance - large images or videos, background size cover, animating CSS \"expensive\" properties... It is probably the best to open an <a href=\"https://github.com/Stanko/react-plx/issues\">GitHub issue</a> with an example on <a href=\"https://codesandbox.io/\">sandbox</a> of yours.\n\nCheers!"
date = "2019-03-04T16:40:48.216Z"
