comment_id = "8f0ae330-3e97-11e9-aec3-5186d7c4cdd5"
slug = "plx-react-parallax-component"
name = "Ryan Calleja"
email = "5e6055069b4650f849679b5601ddf36a"
message = "Hey there,\n\nSuper amazing component ! I love that it is highly customisable and used it well in our desktop version of our platform. \n\nWanted to ask if it is intended to work smoothly on mobile devices ? I gave it a test on iOs and Android but found it quite laggy. Am I missing something ? \n\nThanks a lot for your contribution towards front end development."
date = "2019-03-04T16:07:07.690Z"
