comment_id = "21099750-ff3f-11e9-829e-bd19311bb31b"
slug = "plx-react-parallax-component"
name = "Niklas"
email = "327acedc375f5fd7862310b7d55b1c87"
message = "This is the best f***ing feature I ever used,\nthank you so much for the scaling\n\nPlease continue"
date = "2019-11-04T20:10:21.626Z"
