name: Build and Deploy
on:
  push:
    branches:
      - zola
    paths-ignore:
      - '**/README.md'
      - '**/TODO.md'
      - '**/NOTES.md'
      - '**/LICENSE.md'
      - '**/serve.sh'
      - js/**
      - .vscode/**
  # pull_request:
jobs:
  # Only build PRs
  # Disabled for now
  # build:
  #   runs-on: ubuntu-latest
  #   if: github.ref != 'refs/heads/zola'
  #   steps:
      # - name: 'Checkout'
      #   uses: actions/checkout@master
      # - name: Build
      #   run: sh build-only
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/zola'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Build and deploy
        run: sh build-and-deploy.sh
